# Generated by Django 6.1 on 2026-08-20 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supabase_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('preferred_categories', models.JSONField(blank=True, default=list)),
                ('preferred_brands', models.JSONField(blank=True, default=list)),
                ('typical_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recent_searches', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
