# Generated by Django 6.1 on 2026-08-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
