# Generated by Django 6.1 on 2026-08-20 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWatcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, help_text='Supabase user UUID or guest token', max_length=128)),
                ('search_query', models.CharField(blank=True, help_text="e.g. 'OnePlus Nord' or '5G phone with 6000mAh'", max_length=255)),
                ('condition_type', models.CharField(choices=[('PRICE_DROP', 'Price Drop Below Threshold'), ('STOCK_AVAILABLE', 'Back in Stock Alert'), ('NEW_LAUNCH', 'New Product Launch in Category'), ('REVIEW_RATING_THRESHOLD', 'Community Rating Threshold'), ('DYNAMIC_SPEC_MATCH', 'Dynamic Spec Criteria Match')], default='PRICE_DROP', max_length=32)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dynamic_criteria', models.JSONField(blank=True, default=dict, help_text="e.g. {'battery_min': 5000, 'max_price': 20000}")),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Monitoring'), ('TRIGGERED', 'Condition Met & Notified'), ('CANCELLED', 'Cancelled by User'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='commerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='WatchNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=512)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.product')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='commerce.productwatcher')),
            ],
        ),
    ]
