# Generated by Django 6.1 on 2026-08-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_productwatcher_watchnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='Live inventory & search REST/GraphQL endpoint', max_length=1024),
        ),
        migrations.AddField(
            model_name='merchant',
            name='auth_type',
            field=models.CharField(default='API_KEY', help_text='API_KEY, OAUTH2, HMAC', max_length=50),
        ),
        migrations.AddField(
            model_name='merchant',
            name='brand_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Recognized brand keywords and aliases'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='capability_description',
            field=models.TextField(blank=True, help_text='Rich capability text for AI semantic routing & embeddings'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text="Categories served e.g. ['Audio', 'Wearables']"),
        ),
        migrations.AddField(
            model_name='merchant',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='semantic_embedding',
            field=models.JSONField(blank=True, default=list, help_text='Pre-computed 768-dim/1536-dim text embedding vector'),
        ),
    ]
